[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
panic = "abort"
overflow-checks = false
strip = "symbols"